{
  "_from": "@fastify/error@^4.0.0",
  "_id": "@fastify/error@4.0.0",
  "_inBundle": false,
  "_integrity": "sha512-OO/SA8As24JtT1usTUTKgGH7uLvhfwZPwlptRi2Dp5P4KKmJI3gvsZ8MIHnNwDs4sLf/aai5LzTyl66xr7qMxA==",
  "_location": "/@fastify/error",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "@fastify/error@^4.0.0",
    "name": "@fastify/error",
    "escapedName": "@fastify%2ferror",
    "scope": "@fastify",
    "rawSpec": "^4.0.0",
    "saveSpec": null,
    "fetchSpec": "^4.0.0"
  },
  "_requiredBy": [
    "/avvio",
    "/fastify"
  ],
  "_resolved": "https://registry.npmjs.org/@fastify/error/-/error-4.0.0.tgz",
  "_shasum": "7842d6161fbce78953638318be99033a0c2d5070",
  "_spec": "@fastify/error@^4.0.0",
  "_where": "C:\\Users\\Lenovo\\Repositorios\\node-crud\\node_modules\\fastify",
  "author": {
    "name": "Tomas Della Vedova"
  },
  "bugs": {
    "url": "https://github.com/fastify/fastify-error/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "A small utility, used by Fastify itself, for generating consistent error objects across your codebase and plugins.",
  "devDependencies": {
    "benchmark": "^2.1.4",
    "standard": "^17.1.0",
    "tap": "^18.7.1",
    "tsd": "^0.31.0"
  },
  "homepage": "https://github.com/fastify/fastify-error#readme",
  "keywords": [
    "fastify",
    "error",
    "utility",
    "plugin"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "@fastify/error",
  "publishConfig": {
    "access": "public"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/fastify/fastify-error.git"
  },
  "scripts": {
    "lint": "standard",
    "lint:fix": "standard --fix",
    "test": "npm run test:unit && npm run test:typescript",
    "test:typescript": "tsd",
    "test:unit": "tap"
  },
  "tsd": {
    "compilerOptions": {
      "esModuleInterop": true
    }
  },
  "type": "commonjs",
  "types": "types/index.d.ts",
  "version": "4.0.0"
}
